### ISSUE TITLE
UnsupportedError not reachable when using default features

### ISSUE THREAD

**Issue by aepsil0n** [PistonDevelopers/image#641]
When I import `image 0.13.0` into a fresh project and compile, I'll get this error

```
error[E0001]: unreachable pattern
   --> src/dynimage.rs:632:9
    |
632 |         _ => Err(image::ImageError::UnsupportedError(format!("A decoder for {:?} is not available.", format))),
    |         ^ this is an unreachable pattern

error: aborting due to previous error

error: Could not compile `image`.
```

I guess it is because all the features are active by default and thus there is nothing that can't be handled. Probably should be annotated with a more complex `#[cfg(...)]` thingy to account for this case?

I am doing this on Rust 1.15.1. I am not up-to-date enough to know whether that changes anything.

**Comment by nwin** [comment]
I cannot reproduce this problem with the most recent version of Rust. I tried both rustc 1.19.0 and  1.17.0. It didn’t occur with older versions either. Thus it seems to be an issue temporarily introduced in some Rust version. Is there any specific reason you need to use 1.15.1?

**Comment by aepsil0n** [comment]
No, I was only using it, because that's the latest version shipped with my distro. No problem to update my compiler, but I thought it might be worth bringing it up.

**Comment by abaybektursun** [comment]
For some reason image does not compile with rustc 1.15.1. I had the same version of rust and cargo on Windows, CentOS, Ubuntu machines, and image would not compile. Updating Rust resolved the issue.

Quickly update Rust by running:
`
rustup self uninstall && curl https://sh.rustup.rs -sSf | sh
`

**Comment by aepsil0n** [comment]
Closing this, as there appears to be no reason to make it work with old versions of Rust.
