### ISSUE TITLE
Wrapping arithmetic API has changed in Rust 1.0, breaking compile

### ISSUE THREAD

**Issue by jarrett** [PistonDevelopers/image#416]
Compiling `image` fails with the new Rust 1.0 API. That's because the wrapping arithmetic API has changed. Specifically, functions like `wrapping_shl` have been removed from the numeric types in favor of the new [`Wrapping`](https://doc.rust-lang.org/std/num/struct.Wrapping.html) struct.

I've tried out `Wrapping`, and it works like this:

    use std::num::Wrapping;

    fn main() {
        // 10000001
        let num: u8 = 129;
        let wrapped: Wrapping<u8> = Wrapping(num);
        // 00000010
        let shifted: Wrapping<u8> = wrapped << 1;
        assert_eq!(Wrapping(2u8), shifted);
        let Wrapping(unwrapped_shifted) = shifted;
        assert_eq!(2u8, unwrapped_shifted);
    }

See also https://github.com/PistonDevelopers/image/issues/392, where we decided to use wrapping shifts.

For reference, here is the compiler error:

    /Users/username/.cargo/git/checkouts/image-03876f719561bb08/master/./src/jpeg/decoder.rs:676:16: 676:56 error: type `i32` does not implement any method in scope named `wrapping_shl`
    /Users/username/.cargo/git/checkouts/image-03876f719561bb08/master/./src/jpeg/decoder.rs:676     i32 = 1i32.wrapping_shl((t as u32).wrapping_sub(1));
                                                                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/username/.cargo/git/checkouts/image-03876f719561bb08/master/./src/jpeg/entropy.rs:151:21: 151:46 error: type `u16` does not implement any method in scope named `wrapping_shl`
    /Users/username/.cargo/git/checkouts/image-03876f719561bb08/master/./src/jpeg/entropy.rs:151         code = code.wrapping_shl(diff as u32);

**Comment by bvssvni** [comment]
Has this been fixed already? It compiles fine here.

**Comment by tomaka** [comment]
image 0.3.9 definitely works with Rust 1.0

**Comment by pix64** [comment]
Wrapping doesn't seem to prevent panicking on bit shift operation overflows anyways.

     let a = Wrapping(0u32) << 32;

Results in:

     thread '<main>' panicked at 'shift operation overflowed', C:/bot/slave/stable-dist-rustc-win-64/build/src/libcore\num\wrapping.rs:54

**Comment by jarrett** [comment]
Ouch. Well in that case, we need a new way to solve those panics. Any ideas?

**Comment by pix64** [comment]
As it stands image compiles fine on Rust 1.0.

Apparently in C this is undefined behavior. The result is not guaranteed to be 0. I don't know enough about the JPEG decoder to know what is is trying to accomplish, but I did "fix" this issue here https://github.com/PistonDevelopers/image/pull/412 .

By adding checks if the shift amount is greater than the variable length. I do not know if this is the correct behavior but it does make debug builds build and act the same as release builds.

**Comment by jarrett** [comment]
Alright. I'll close this for now. If I can figure out what, if anything, is wrong, I'll open a new issue with a more clear description.

**Comment by ruud-v-a** [comment]
I had problems with the shifts in a crate of mine as well. The way to avoid it, is to ensure not to shift by the width of the type or more.
