### ISSUE TITLE
Compilation error with 0.12.4 and `default-features = false`

### ISSUE THREAD

**Issue by kaegi** [PistonDevelopers/image#644]
Compiling version 0.12.4 as a dependency with `default-features = false` leads to compilation errors. 
All projects that build on `0.12.*` with that setting will therefore not be able to compile anymore.

```
error[E0004]: non-exhaustive patterns: type image::ImageFormat is non-empty
   --> /home/_/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.12.4/./src/dynimage.rs:611:11
    |
611 |     match format {
    |           ^^^^^^
    |
help: Please ensure that all possible cases are being handled; possibly adding wildcards or more match arms.
   --> /home/_/.cargo/registry/src/github.com-1ecc6299db9ec823/image-0.12.4/./src/dynimage.rs:611:11
    |
611 |     match format {
    |           ^^^^^^

error: aborting due to previous error

error: Could not compile `image`.
```

**Comment by nwin** [comment]
Closing as duplicate of #645.

**Comment by kaegi** [comment]
I don't think it's a duplicate, because changing the version to 0.13.0 does work (leaving `default-features = false`). [Here](https://github.com/emk/subtitles-rs/pull/6) is a pull request for some crates that are affected by the compilation error in 0.12.4 but work fine when updating to 0.13.0.
